[package]
name = "rust_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "channels"
path = "src/bin/example2.rs"

[[bin]]
name = "ownership"
path = "src/bin/example3.rs"


[dependencies]
